### ISSUE TITLE
Test behavior and options need better documentation

### ISSUE THREAD

**Issue by varl** [dhis2/app-platform#269]
In a structure where `src` and `test` directories are siblings:

```
varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test
yarn run v1.21.1
$ d2-app-scripts test
Running tests... 
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/varl/dev/dhis2/libs/ui-core
  147 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 147 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
error Command failed with exit code 1.
```

Passing in a [testRegexp](https://github.com/dhis2/app-platform/blob/master/cli/src/commands/test.js#L76) does not work:

```
varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test test/
yarn run v1.21.1
$ d2-app-scripts test test/
Running tests... 
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/varl/dev/dhis2/libs/ui-core
  147 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 147 matches
  testRegex:  - 0 matches
Pattern: t|e|s|t|/ - 0 matches
error Command failed with exit code 1.

varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test test/*.test.js
yarn run v1.21.1
$ d2-app-scripts test test/StackedTable.test.js
Running tests... 
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/varl/dev/dhis2/libs/ui-core
  147 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 147 matches
  testRegex:  - 0 matches
Pattern: t|e|s|t|/|S|t|a|c|k|e|d|T|a|b|l|e|.|t|e|s|t|.|j|s - 0 matches
error Command failed with exit code 1.
```

Using quotes around the `testRegexp` does not help:

```
varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test 'test/*.test.js'
yarn run v1.21.1
$ d2-app-scripts test 'test/*.test.js'
Running tests... 
  Invalid testPattern t|e|s|t|/|*|.|t|e|s|t|.|j|s supplied. Running all tests instead.
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/varl/dev/dhis2/libs/ui-core
  147 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 147 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
error Command failed with exit code 1.

varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test "test/*.test.js"
yarn run v1.21.1
$ d2-app-scripts test 'test/*.test.js'
Running tests... 
  Invalid testPattern t|e|s|t|/|*|.|t|e|s|t|.|j|s supplied. Running all tests instead.
No tests found, exiting with code 1
Run with `--passWithNoTests` to exit with code 0
In /home/varl/dev/dhis2/libs/ui-core
  147 files checked.
  testMatch: **/__tests__/**/*.[jt]s?(x), **/?(*.)+(spec|test).[tj]s?(x) - 0 matches
  testPathIgnorePatterns: /node_modules/ - 147 matches
  testRegex:  - 0 matches
Pattern:  - 0 matches
error Command failed with exit code 1.
```

Moving the `test/` directory to `src/__tests__` runs the tests (but fails):

```
varl@veronika:~/dev/dhis2/libs/ui-core$ mv test/ src/__tests__
varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test
yarn run v1.21.1
$ d2-app-scripts test
Running tests... 
[ERROR] Test script exited with non-zero exit code 
error Command failed with exit code 1.
```

The `setupTests.js` file is run as a test:

```
varl@veronika:~/dev/dhis2/libs/ui-core$ yarn test
yarn run v1.21.1
$ d2-app-scripts test
Running tests... 
 FAIL  src/__tests__/StackedTable.test.js
  # Test suite failed to run

    Cannot find module '../src/index.js' from 'StackedTable.test.js'

      4 | import { mount } from 'enzyme'
      5 | 
    > 6 | import {
        | ^
      7 |     StackedTable,
      8 |     StackedTableBody,
      9 |     StackedTableCell,

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:259:17)
      at Object.<anonymous> (src/__tests__/StackedTable.test.js:6:1)

 FAIL  src/__tests__/setupTests.js
  # Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/@jest/core/build/TestScheduler.js:242:24
      at asyncGeneratorStep (node_modules/@jest/core/build/TestScheduler.js:131:24)
      at _next (node_modules/@jest/core/build/TestScheduler.js:151:9)
      at node_modules/@jest/core/build/TestScheduler.js:156:7
      at node_modules/@jest/core/build/TestScheduler.js:148:12
      at onResult (node_modules/@jest/core/build/TestScheduler.js:271:25)
          at async Promise.all (index 0)

Test Suites: 2 failed, 2 total
Tests:       0 total
Snapshots:   0 total
Time:        1.029s
Ran all test suites.
[ERROR] Tests failed 
error Command failed with exit code 1.
```

And even if we pass in `*.test.js` as a `testRegexp` pattern, that is ignored:

```
$ d2-app-scripts test '*.test.js'
Running tests... 
  Invalid testPattern *|.|t|e|s|t|.|j|s supplied. Running all tests instead.
[...]
```

So there are multiple problems:

1. `testRegexp` is not respected (or not intuitive to use)
2. Test directory is assumed to always be `__tests__`
3. Test directory root is hardcoded to `src`

**Comment by amcgee** [comment]
@varl as discussed in slack, we're pretty sure everything works "as expected" here.  The `test` command and configuration options are woefully under-documented and the defaults might need tweaking, though.

**Comment by Megnatis** [comment]
Hello I got this error on dashboard-app for start or build.
